
on:
  # Trigger analysis when pushing in master or pull requests, and when creating
  # a pull request. 
  push:
    branches:
      - master
  pull_request:
      types: [opened, synchronize, reopened]
name: Main Workflow
jobs:
  sonarcloud:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Setup sonarqube
      uses: warchant/setup-sonar-scanner@v1
    - name: Run sonarqube 
      env:
        GITHUB_TOKEN: ${{secrets.githubtoken}}
        
      run: sonar-scanner
       -Dsonar.login=${{secrets.sonar_token}}
       -Dsonar.organization=jerry-zhang-dyg
       -Dsonar.host.url=https://sonarcloud.io/
       -Dsonar.projectKey=jerry-zhang-DYG_Jsforscan
